# Generated by Django 6.0.7 on 2026-07-11 14:18

import assignments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_enabled",
                    models.BooleanField(default=False, verbose_name="启用自动备份"),
                ),
                (
                    "backup_interval",
                    models.PositiveIntegerField(
                        default=60, verbose_name="备份间隔 (分钟)"
                    ),
                ),
                (
                    "auto_cleanup_enabled",
                    models.BooleanField(default=False, verbose_name="启用自动清理"),
                ),
                (
                    "cleanup_after_backup",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="0=立即清理，留空=不自动清理",
                        verbose_name="备份成功后清理本地存档 (天数)",
                    ),
                ),
                (
                    "webdav_url",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="WebDAV URL"
                    ),
                ),
                (
                    "webdav_username",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="WebDAV 用户名"
                    ),
                ),
                (
                    "webdav_password",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="WebDAV 密码"
                    ),
                ),
                (
                    "s3_endpoint",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="S3 Endpoint"
                    ),
                ),
                (
                    "s3_access_key",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="S3 Access Key"
                    ),
                ),
                (
                    "s3_secret_key",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="S3 Secret Key"
                    ),
                ),
                (
                    "s3_bucket",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="S3 Bucket"
                    ),
                ),
                (
                    "s3_region",
                    models.CharField(
                        blank=True,
                        default="us-east-1",
                        max_length=128,
                        verbose_name="S3 Region",
                    ),
                ),
                (
                    "smb_host",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="SMB Host"
                    ),
                ),
                (
                    "smb_share",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="SMB Share"
                    ),
                ),
                (
                    "smb_username",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="SMB 用户名"
                    ),
                ),
                (
                    "smb_password",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="SMB 密码"
                    ),
                ),
                (
                    "smb_domain",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="SMB Domain"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="项目名称")),
                (
                    "slug",
                    models.SlugField(
                        help_text="用于文件目录命名",
                        max_length=128,
                        unique=True,
                        verbose_name="标识",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "auto_rename",
                    models.BooleanField(default=True, verbose_name="启用自动重命名"),
                ),
                (
                    "rename_pattern",
                    models.CharField(
                        default="{student_id} {name}",
                        help_text="可用变量: {student_id}, {name}, {project}, {timestamp}, {original_name}, {ext}",
                        max_length=256,
                        verbose_name="重命名正则模板",
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("local", "本地存储"),
                            ("webdav", "WebDAV"),
                            ("s3", "Amazon S3"),
                            ("smb", "SMB 共享"),
                        ],
                        default="local",
                        max_length=32,
                        verbose_name="存储后端",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "max_file_size",
                    models.PositiveIntegerField(
                        default=50, verbose_name="最大文件大小 (MB)"
                    ),
                ),
                (
                    "allowed_extensions",
                    models.CharField(
                        blank=True,
                        help_text="逗号分隔，如 .pdf,.docx,.zip，留空则允许所有",
                        max_length=512,
                        verbose_name="允许的文件类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "作业项目",
                "verbose_name_plural": "作业项目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=assignments.models.submission_upload_to,
                        verbose_name="作业文件",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=512, verbose_name="原始文件名"),
                ),
                (
                    "renamed_filename",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="重命名后文件名"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小 (bytes)"
                    ),
                ),
                (
                    "auto_renamed",
                    models.BooleanField(default=False, verbose_name="自动重命名"),
                ),
                ("appeal", models.TextField(blank=True, verbose_name="申诉内容")),
                (
                    "appeal_submitted",
                    models.BooleanField(default=False, verbose_name="已提交申诉"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.project",
                        verbose_name="作业项目",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "提交记录",
                "verbose_name_plural": "提交记录",
                "ordering": ["-submitted_at"],
                "unique_together": {("project", "student")},
            },
        ),
    ]
